import { create } from "zustand";
import { subscribeWithSelector } from "zustand/middleware";
import { produce } from "immer";
import {
  listen,
  type EventCallback,
  type UnlistenFn,
} from "@tauri-apps/api/event";
import { commands, type ModelInfo } from "@/bindings";

interface DownloadProgress {
  model_id: string;
  generation: number;
  downloaded: number;
  total: number;
  percentage: number;
}

// Not (yet) generated by tauri-specta in bindings.ts — the Rust struct exists
// but bindings.ts is only regenerated on a Rust build. Defined locally so
// tsc passes; replace with an import from "@/bindings" once it appears there.
interface DownloadEvent {
  model_id: string;
  generation: number;
  error?: string | null;
}

interface DownloadStats {
  startTime: number;
  lastUpdate: number;
  totalDownloaded: number;
  speed: number; // MB/s
}

// An event is stale if it belongs to an older attempt than the latest
// generation we've already observed for that model — e.g. a delayed
// progress/terminal event from a download the user cancelled and restarted.
// Such events must be ignored entirely so they can't clobber newer state.
function isStale(
  downloadGenerations: Record<string, number>,
  modelId: string,
  generation: number,
): boolean {
  return generation < (downloadGenerations[modelId] ?? 0);
}

// True once an attempt's generation has already reached a terminal state.
// Terminal handlers use this for idempotence (a second terminal event for the
// same generation is a no-op); non-terminal handlers (progress,
// extraction-started/completed) use it so a reordered same-generation event
// can't reopen an already-terminated attempt.
function isTerminated(
  terminalGenerations: Record<string, number>,
  modelId: string,
  generation: number,
): boolean {
  return generation <= (terminalGenerations[modelId] ?? 0);
}

// Using Record instead of Set/Map for Immer compatibility
interface ModelsStore {
  models: ModelInfo[];
  currentModel: string;
  downloadingModels: Record<string, true>;
  extractingModels: Record<string, true>;
  downloadProgress: Record<string, DownloadProgress>;
  downloadStats: Record<string, DownloadStats>;
  // Latest generation seen per model id, across all download lifecycle
  // events. Used to detect and drop stale (superseded-attempt) events.
  downloadGenerations: Record<string, number>;
  // Highest generation that has already reached a TERMINAL state
  // (complete/cancelled/error/extraction-failed) per model id. A progress
  // event whose generation is <= this fence is ignored, so a reordered
  // same-generation progress event cannot reopen an attempt the terminal
  // event already closed.
  terminalGenerations: Record<string, number>;
  loading: boolean;
  error: string | null;
  hasAnyModels: boolean;
  isFirstRun: boolean;
  initialized: boolean;

  // Actions
  initialize: () => Promise<void>;
  loadModels: () => Promise<void>;
  loadCurrentModel: () => Promise<void>;
  checkFirstRun: () => Promise<boolean>;
  selectModel: (modelId: string) => Promise<boolean>;
  downloadModel: (modelId: string) => Promise<boolean>;
  cancelDownload: (modelId: string) => Promise<boolean>;
  deleteModel: (modelId: string) => Promise<boolean>;
  getModelInfo: (modelId: string) => ModelInfo | undefined;
  isModelDownloading: (modelId: string) => boolean;
  isModelExtracting: (modelId: string) => boolean;
  getDownloadProgress: (modelId: string) => DownloadProgress | undefined;

  // Internal setters
  setModels: (models: ModelInfo[]) => void;
  setCurrentModel: (modelId: string) => void;
  setError: (error: string | null) => void;
  setLoading: (loading: boolean) => void;
}

export const useModelStore = create<ModelsStore>()(
  subscribeWithSelector((set, get) => ({
    models: [],
    currentModel: "",
    downloadingModels: {},
    extractingModels: {},
    downloadProgress: {},
    downloadStats: {},
    downloadGenerations: {},
    terminalGenerations: {},
    loading: true,
    error: null,
    hasAnyModels: false,
    isFirstRun: false,
    initialized: false,

    // Internal setters
    setModels: (models) => set({ models }),
    setCurrentModel: (currentModel) => set({ currentModel }),
    setError: (error) => set({ error }),
    setLoading: (loading) => set({ loading }),

    loadModels: async () => {
      try {
        const result = await commands.getAvailableModels();
        if (result.status === "ok") {
          set({ models: result.data, error: null });

          // Sync downloading state from backend
          set(
            produce((state) => {
              const backendDownloading: Record<string, true> = {};
              result.data
                .filter((m) => m.is_downloading)
                .forEach((m) => {
                  backendDownloading[m.id] = true;
                });

              // Merge: keep frontend state if downloading, add backend state
              Object.keys(backendDownloading).forEach((id) => {
                state.downloadingModels[id] = true;
              });

              // Remove models that backend says are NOT downloading AND
              // frontend doesn't have progress for (completed/cancelled)
              Object.keys(state.downloadingModels).forEach((id) => {
                if (!backendDownloading[id] && !state.downloadProgress[id]) {
                  delete state.downloadingModels[id];
                }
              });
            }),
          );
        } else {
          set({ error: `Failed to load models: ${result.error}` });
        }
      } catch (err) {
        set({ error: `Failed to load models: ${err}` });
      } finally {
        set({ loading: false });
      }
    },

    loadCurrentModel: async () => {
      try {
        const result = await commands.getCurrentModel();
        if (result.status === "ok") {
          set({ currentModel: result.data });
        }
      } catch (err) {
        console.error("Failed to load current model:", err);
      }
    },

    checkFirstRun: async () => {
      try {
        const result = await commands.hasAnyModelsAvailable();
        if (result.status === "ok") {
          const hasModels = result.data;
          set({ hasAnyModels: hasModels, isFirstRun: !hasModels });
          return !hasModels;
        }
        return false;
      } catch (err) {
        console.error("Failed to check model availability:", err);
        return false;
      }
    },

    selectModel: async (modelId: string) => {
      try {
        set({ error: null });
        const result = await commands.setActiveModel(modelId);
        if (result.status === "ok") {
          set({
            currentModel: modelId,
            isFirstRun: false,
            hasAnyModels: true,
          });
          return true;
        } else {
          set({ error: `Failed to switch to model: ${result.error}` });
          return false;
        }
      } catch (err) {
        set({ error: `Failed to switch to model: ${err}` });
        return false;
      }
    },

    downloadModel: async (modelId: string) => {
      // If a download for this model is already showing, another attempt owns
      // its UI state — don't optimistically overwrite it (which would zero a
      // live attempt's progress), and don't clear it if THIS call fails.
      const alreadyShowing = !!get().downloadingModels[modelId];
      try {
        set({ error: null });
        if (!alreadyShowing) {
          set(
            produce((state) => {
              state.downloadingModels[modelId] = true;
              state.downloadProgress[modelId] = {
                model_id: modelId,
                generation: state.downloadGenerations[modelId] ?? 0,
                downloaded: 0,
                total: 0,
                percentage: 0,
              };
            }),
          );
        }
        const result = await commands.downloadModel(modelId);
        if (result.status === "ok") {
          return true;
        } else {
          // Do NOT clear per-model records here. A genuine post-admission
          // failure of THIS attempt is reported by a generation-scoped
          // `model-download-error` event (from the backend's RegistrationGuard),
          // which clears exactly this attempt's state. An ALREADY_DOWNLOADING
          // rejection means another attempt owns the model — also nothing for
          // us to clear. Only set the error banner for user feedback.
          set({ error: `Failed to download model: ${result.error}` });
          return false;
        }
      } catch (err) {
        set({ error: `Failed to download model: ${err}` });
        if (!alreadyShowing) {
          set(
            produce((state) => {
              delete state.downloadingModels[modelId];
              delete state.downloadProgress[modelId];
              delete state.downloadStats[modelId];
              delete state.extractingModels[modelId];
            }),
          );
        }
        return false;
      }
    },

    cancelDownload: async (modelId: string) => {
      try {
        set({ error: null });
        const result = await commands.cancelDownload(modelId);
        if (result.status === "ok") {
          // Don't eagerly clear-then-reload here: the backend emits
          // model-download-cancelled AFTER it clears its own state, and
          // that event (generation-checked, like all the others) is what
          // drives the actual cleanup. Reloading immediately here risked
          // reading still-live backend state and racing a delayed event
          // from this very attempt.
          return true;
        } else {
          set({ error: `Failed to cancel download: ${result.error}` });
          return false;
        }
      } catch (err) {
        set({ error: `Failed to cancel download: ${err}` });
        return false;
      }
    },

    deleteModel: async (modelId: string) => {
      try {
        set({ error: null });
        const result = await commands.deleteModel(modelId);
        if (result.status === "ok") {
          await get().loadModels();
          await get().loadCurrentModel();
          return true;
        } else {
          set({ error: `Failed to delete model: ${result.error}` });
          return false;
        }
      } catch (err) {
        set({ error: `Failed to delete model: ${err}` });
        return false;
      }
    },

    getModelInfo: (modelId: string) => {
      return get().models.find((model) => model.id === modelId);
    },

    isModelDownloading: (modelId: string) => {
      return modelId in get().downloadingModels;
    },

    isModelExtracting: (modelId: string) => {
      return modelId in get().extractingModels;
    },

    getDownloadProgress: (modelId: string) => {
      return get().downloadProgress[modelId];
    },

    initialize: async () => {
      if (get().initialized) return;

      const { loadModels, loadCurrentModel, checkFirstRun } = get();

      // Register event listeners BEFORE loading the initial snapshot, and AWAIT
      // their registration below, so a lifecycle event that fires during startup
      // — including the sole generation-scoped `model-download-error` cleanup
      // event — is never missed (and a registration failure surfaces before the
      // store is marked initialized). `on(...)` collects each listen promise.
      const registrations: Promise<UnlistenFn>[] = [];
      const on = <T>(name: string, handler: EventCallback<T>) => {
        registrations.push(listen<T>(name, handler));
      };

      // Set up event listeners
      on<DownloadProgress>("model-download-progress", (event) => {
        const progress = event.payload;
        const { model_id, generation } = progress;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        // Terminal fence: if this generation already reached a terminal state,
        // a reordered same-generation progress event must NOT reopen it.
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        // A strictly newer generation means a new attempt — drop the previous
        // attempt's speed stats so its baseline can't produce a false burst.
        const isNewGeneration =
          generation > (get().downloadGenerations[model_id] ?? 0);
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            if (isNewGeneration) {
              delete state.downloadStats[model_id];
            }
            state.downloadProgress[model_id] = progress;
            // Restore the downloading flag: an older attempt's terminal event
            // (which clears downloadingModels) can be processed just before this
            // fresh attempt's first progress event; without this, the bar would
            // show progress while the flag stays false for the whole retry.
            state.downloadingModels[model_id] = true;
          }),
        );

        // Update download stats for speed calculation
        const now = Date.now();
        set(
          produce((state) => {
            const current = state.downloadStats[model_id];

            if (!current) {
              state.downloadStats[model_id] = {
                startTime: now,
                lastUpdate: now,
                totalDownloaded: progress.downloaded,
                speed: 0,
              };
            } else {
              const timeDiff = (now - current.lastUpdate) / 1000;
              const bytesDiff = progress.downloaded - current.totalDownloaded;

              if (timeDiff > 0.5) {
                const currentSpeed = bytesDiff / (1024 * 1024) / timeDiff;
                const validCurrentSpeed = Math.max(0, currentSpeed);
                const smoothedSpeed =
                  current.speed > 0
                    ? current.speed * 0.8 + validCurrentSpeed * 0.2
                    : validCurrentSpeed;

                state.downloadStats[model_id] = {
                  startTime: current.startTime,
                  lastUpdate: now,
                  totalDownloaded: progress.downloaded,
                  speed: Math.max(0, smoothedSpeed),
                };
              }
            }
          }),
        );
      });

      on<DownloadEvent>("model-download-complete", (event) => {
        const { model_id, generation } = event.payload;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        // Idempotent: a second terminal event for this generation is a no-op.
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            state.terminalGenerations[model_id] = Math.max(
              state.terminalGenerations[model_id] ?? 0,
              generation,
            );
            delete state.downloadingModels[model_id];
            delete state.downloadProgress[model_id];
            delete state.downloadStats[model_id];
            delete state.extractingModels[model_id];
          }),
        );
        get().loadModels();
      });

      on<DownloadEvent>("model-extraction-started", (event) => {
        const { model_id, generation } = event.payload;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        // Don't re-open extraction for an attempt that already terminated.
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            state.extractingModels[model_id] = true;
          }),
        );
      });

      on<DownloadEvent>("model-extraction-completed", (event) => {
        const { model_id, generation } = event.payload;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            delete state.extractingModels[model_id];
          }),
        );
        get().loadModels();
      });

      on<DownloadEvent>("model-extraction-failed", (event) => {
        const { model_id, generation, error } = event.payload;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            state.terminalGenerations[model_id] = Math.max(
              state.terminalGenerations[model_id] ?? 0,
              generation,
            );
            delete state.downloadingModels[model_id];
            delete state.downloadProgress[model_id];
            delete state.downloadStats[model_id];
            delete state.extractingModels[model_id];
            // Only surface the global error banner if this failure is for
            // the model the user currently has selected — an abandoned
            // model's failure shouldn't clobber the UI while viewing/using
            // a different one.
            if (model_id === state.currentModel) {
              state.error = `Failed to extract model: ${error}`;
            }
          }),
        );
      });

      on<DownloadEvent>("model-download-cancelled", (event) => {
        const { model_id, generation } = event.payload;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            state.terminalGenerations[model_id] = Math.max(
              state.terminalGenerations[model_id] ?? 0,
              generation,
            );
            delete state.downloadingModels[model_id];
            delete state.downloadProgress[model_id];
            delete state.downloadStats[model_id];
            delete state.extractingModels[model_id];
          }),
        );
      });

      // A download attempt failed on the backend (an armed RegistrationGuard
      // drop). Generation-scoped so it only ever clears THIS attempt's state,
      // never a newer retry's — the frontend no longer has to guess cleanup
      // from the command return value.
      on<DownloadEvent>("model-download-error", (event) => {
        const { model_id, generation, error } = event.payload;
        if (isStale(get().downloadGenerations, model_id, generation)) {
          return;
        }
        if (isTerminated(get().terminalGenerations, model_id, generation)) {
          return;
        }
        set(
          produce((state) => {
            state.downloadGenerations[model_id] = Math.max(
              state.downloadGenerations[model_id] ?? 0,
              generation,
            );
            state.terminalGenerations[model_id] = Math.max(
              state.terminalGenerations[model_id] ?? 0,
              generation,
            );
            delete state.downloadingModels[model_id];
            delete state.downloadProgress[model_id];
            delete state.downloadStats[model_id];
            delete state.extractingModels[model_id];
            if (model_id === state.currentModel) {
              state.error = `Failed to download model: ${error}`;
            }
          }),
        );
      });

      on<string>("model-deleted", () => {
        get().loadModels();
        get().loadCurrentModel();
      });

      on("model-state-changed", () => {
        get().loadModels();
        get().loadCurrentModel();
      });

      // Await listener registration, THEN load the initial snapshot, THEN mark
      // initialized — so no startup event is missed and a registration failure
      // is surfaced before the store is exposed as ready.
      await Promise.all(registrations);
      await Promise.all([loadModels(), loadCurrentModel(), checkFirstRun()]);

      set({ initialized: true });
    },
  })),
);
