
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodPttSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_ptt_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSubmitPasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_submit_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteLastPasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_last_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteLastClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_last_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSubmitIdleBehaviorSetting(behavior: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_submit_idle_behavior_setting", { behavior }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSubmitClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_submit_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardRestoreDelaySetting(delay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_restore_delay_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSubmitClipboardRestoreDelaySetting(delay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_submit_clipboard_restore_delay_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperSubmitDelaySetting(delay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_submit_delay_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperPasteDelaySetting(delay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_paste_delay_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperSubmitDelayRemoteSetting(delay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_submit_delay_remote_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperPasteDelayRemoteSetting(delay: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_paste_delay_remote_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setJumperRemoteMatchStrings(strings: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_jumper_remote_match_strings", { strings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getShortcutRegistrationFailures() : Promise<RegistrationFailure[]> {
    return await TAURI_INVOKE("get_shortcut_registration_failures");
},
async changeReturnFocusSetting(flow: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_return_focus_setting", { flow, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnchorStatus() : Promise<AnchorStatus | null> {
    return await TAURI_INVOKE("get_anchor_status");
},
async clearAnchor() : Promise<void> {
    return await TAURI_INVOKE("clear_anchor");
},
async getJumpSlots() : Promise<(AnchorStatus | null)[]> {
    return await TAURI_INVOKE("get_jump_slots");
},
async clearJumpSlot(slot: number) : Promise<void> {
    return await TAURI_INVOKE("clear_jump_slot", { slot });
},
async jumpToSlot(slot: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jump_to_slot", { slot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperPersistSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_persist_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAnchorActionSlotSetting(key: string, slot: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_anchor_action_slot_setting", { key, slot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperTrackSetting(flow: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_track_setting", { flow, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperTrackSlotSetting(flow: string, slot: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_track_slot_setting", { flow, slot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperSaveCursorSlot(slot: number, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_save_cursor_slot", { slot, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeJumperCursorModeSlot(slot: number, mode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_jumper_cursor_mode_slot", { slot, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAnchorRequireSameFlow(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_anchor_require_same_flow", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslatorModelUnloadTimeout(timeout: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translator_model_unload_timeout", { timeout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslatorModelUnloadCustomSeconds(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translator_model_unload_custom_seconds", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranslatorStatus() : Promise<Result<TranslatorStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_translator_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslatorEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translator_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslatorPriority(priority: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translator_priority", { priority }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslatorModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translator_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async translatorAddFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("translator_add_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async translatorSetFolderEnabled(path: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("translator_set_folder_enabled", { path, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async translatorRemoveFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("translator_remove_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAnchorActionSetting(key: string, action: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_anchor_action_setting", { key, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelUnloadCustomSeconds(seconds: number) : Promise<void> {
    return await TAURI_INVOKE("set_model_unload_custom_seconds", { seconds });
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCancelBehaviorSetting(behavior: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_cancel_behavior_setting", { behavior }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscriptionModeSetting(mode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcription_mode_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscriptionModePttSetting(mode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcription_mode_ptt_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDeviceSetting(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device_setting", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeApiTranscriptionUrlSetting(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_api_transcription_url_setting", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeApiTranscriptionKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_api_transcription_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeApiTranscriptionModelSetting(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_api_transcription_model_setting", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOpenrouterTranscriptionUrlSetting(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_openrouter_transcription_url_setting", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOpenrouterTranscriptionKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_openrouter_transcription_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOpenrouterTranscriptionModelSetting(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_openrouter_transcription_model_setting", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOpenrouterTranscriptionRouteSetting(route: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_openrouter_transcription_route_setting", { route }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOpenrouterTranscriptionAudioFormatSetting(format: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_openrouter_transcription_audio_format_setting", { format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateModelTestLibrary(library: ModelTestLibrary) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_model_test_library", { library }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Select which registered LLM provider (by stable id) post-processing uses.
 * An empty id clears the selection.
 */
async setPostProcessProviderRef(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider_ref", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessTemperatureSetting(temperature: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_temperature_setting", { temperature }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCrashResilientRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_crash_resilient_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTypingStartDelaySetting(delay: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_start_delay_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTypingKeyDelaySetting(delay: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_key_delay_setting", { delay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changePostProcessDisableThinkingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_disable_thinking_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Count tokens in text using the specified tokenizer.
 */
async countTokens(text: string, tokenizer: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_tokens", { text, tokenizer }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Check if FLM (FastFlowLM) is available on this system.
 */
async checkFlmAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_flm_available");
},
async openFloatingTranscription() : Promise<void> {
    await TAURI_INVOKE("open_floating_transcription");
},
async closeFloatingTranscription() : Promise<void> {
    await TAURI_INVOKE("close_floating_transcription");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTypingText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_typing_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTyping(delaySecs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_typing", { delaySecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTyping() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_typing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countTokensViaProvider(providerId: string, text: string) : Promise<Result<ProviderCountResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_tokens_via_provider", { providerId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Counts with the built-in tokenizers (always first, serialized â€” they are
 * instant) and then every enabled provider. Failures are silent: each
 * provider's error is recorded in its result and the sweep continues.
 * Results are also emitted one-by-one as `token-count-progress` events.
 * 
 * `parallel` selects the provider strategy:
 * - `false` (serialized): one provider at a time. Right when several slots
 * share one local service that must load/unload each model â€” parallel
 * requests would just thrash the loader.
 * - `true`: all providers queried at once; total time = slowest provider.
 * Right for independent services and cloud APIs.
 */
async countTokensAllProviders(text: string, parallel: boolean) : Promise<Result<ProviderCountResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_tokens_all_providers", { text, parallel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTokenCountSweep() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_token_count_sweep") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists the models a provider offers, queried live from its API.
 */
async listProviderModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists OpenRouter speech-to-text models. The default `/models` list EXCLUDES
 * STT models, so this queries `?output_modalities=transcription` (public â€” no
 * key required). Falls back to a curated list on any error so the picker is
 * never empty. Used specifically by the OpenRouter-transcription model picker.
 */
async listOpenrouterTranscriptionModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_openrouter_transcription_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a text file for the Token Count page. Done backend-side so the
 * frontend fs scope (limited to $APPDATA) doesn't need widening.
 */
async readTextFileForCount(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_text_file_for_count", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runModelTest(system: string | null, prompt: string, providerIds: string[], temperature: number, thinking: boolean | null, imageDataUrl: string | null) : Promise<Result<ModelTestRun, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_model_test", { system, prompt, providerIds, temperature, thinking, imageDataUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelModelTest() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_model_test") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a UTF-8 text file (used to export the model-testing Markdown report).
 * The frontend picks the path via the save dialog; writing on the backend
 * avoids widening the frontend's `$APPDATA`-scoped filesystem permissions.
 */
async writeTextFile(path: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_text_file", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch OpenRouter's public model catalogue with pass-through pricing,
 * normalized to USD per 1M tokens. Public endpoint â€” no API key needed. The UI
 * uses this to auto-fill cost fields, including for Gemini/Anthropic models via
 * their OpenRouter slugs (those providers don't expose pricing themselves).
 */
async fetchOpenrouterModelPrices() : Promise<Result<OpenRouterModelPrice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_openrouter_model_prices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMcpStatus() : Promise<McpStatus> {
    return await TAURI_INVOKE("get_mcp_status");
},
async setMcpEnabled(enabled: boolean) : Promise<Result<McpStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mcp_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMcpPort(port: number) : Promise<Result<McpStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mcp_port", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async regenerateMcpToken() : Promise<Result<McpStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("regenerate_mcp_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installCli() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_cli") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLlmProviders(providers: LlmProvider[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_llm_providers", { providers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the GPU adapters whisper.cpp's Vulkan backend can see, for the
 * transcription GPU-device selector. Enumeration is lazy (queries the
 * Vulkan backend on demand) and safe to call at any time — it never touches
 * a loaded model. Returns an empty list on macOS (Metal backend, no Vulkan
 * device registry) or if no adapters are found.
 */
async listGpuDevices() : Promise<Result<GpuDeviceOption[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_gpu_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries() : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recompute duration_seconds for history rows missing it (e.g. recordings made
 * before duration tracking) by reading each audio file. Returns rows updated.
 */
async backfillHistoryDurations() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backfill_history_durations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a `.tar.gz` backup at `dest_path`. `profile` is "config" or "full".
 */
async createBackup(profile: string, destPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_backup", { profile, destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreBackup(archivePath: string, includeConfig: boolean, includeRecordings: boolean) : Promise<Result<RestoreReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_backup", { archivePath, includeConfig, includeRecordings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartApp() : Promise<void> {
    await TAURI_INVOKE("restart_app");
},
/**
 * Stub implementation for non-macOS platforms
 * Always returns false since laptop detection is macOS-specific
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; typing_start_delay_secs?: number; typing_key_delay_ms?: number; selected_model?: string;
/**
 * Vulkan GPU device selection for local Whisper transcription (T-212).
 * Sentinel-encoded rather than a parallel accelerator enum: `-1`
 * (default) = Auto (whisper.cpp's own default: GPU on, device 0 — the
 * behavior before this setting existed), `-2` = force CPU, `>= 0` = an
 * explicit Vulkan device index from `list_gpu_devices`. Applied at
 * Whisper model load (`managers/transcription.rs`); an adapter that
 * fails to init (disappeared, stale index, driver reordering) falls
 * back to Auto rather than bricking transcription.
 */
transcribe_gpu_device?: number; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition;
/**
 * UI appearance: System (follows OS), Light, or Dark. Resolved and
 * applied by the frontend (main window via React; the overlay/floating
 * windows via a Rust-side push since they have no settings store — see
 * `apply_theme_to_aux_windows` in lib.rs).
 */
app_theme?: Theme; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; model_unload_custom_seconds?: number; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; paste_method_ptt?: PasteMethod; clipboard_handling?: ClipboardHandling; paste_last_paste_method?: PasteMethod; paste_last_clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; 
/**
 * Unified registry of LLM providers powering token counting,
 * post-processing, and the model-testing tool. Aliased from the old
 * `token_count_providers` key so existing configs (and their API keys)
 * migrate automatically on first load.
 */
llm_providers?: LlmProvider[]; 
/**
 * Stable id (into `llm_providers`) of the provider used for
 * post-processing. Empty when not yet configured.
 */
post_process_provider_ref?: string; 
/**
 * Sampling temperature for post-processing (0.0 = most deterministic).
 */
post_process_temperature?: number; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; crash_resilient_recording?: boolean; app_language?: string; experimental_enabled?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; transcription_mode?: TranscriptionMode; transcription_mode_ptt?: TranscriptionMode; api_transcription_url?: string; api_transcription_key?: string; api_transcription_model?: string; post_process_disable_thinking?: boolean; 
/**
 * Registry provider id (kind `openrouter`) supplying the base URL + API key
 * for OpenRouter transcription.
 */
openrouter_transcription_provider_ref?: string; 
/**
 * Transcription model id (e.g. `openai/whisper-large-v3` or
 * `google/gemini-2.5-flash`).
 */
openrouter_transcription_model?: string; openrouter_transcription_route?: OpenRouterTranscriptionRoute; openrouter_transcription_audio_format?: TranscriptionAudioFormat; openrouter_transcription_url?: string; openrouter_transcription_key?: string; openrouter_transcription_language?: string; openrouter_transcription_translate_to_english?: boolean; api_transcription_language?: string; api_transcription_translate_to_english?: boolean; custom_asr_config_migrated?: boolean;
/**
 * Saved prompts + presets for the model-testing tool.
 */
model_test_library?: ModelTestLibrary; 
/**
 * Expose a localhost MCP + CLI server so the app can be driven by Claude
 * (app/Code) and the `handy` CLI.
 */
mcp_server_enabled?: boolean; 
/**
 * Port the localhost MCP/CLI server binds to (127.0.0.1 only).
 */
mcp_server_port?: number; 
/**
 * Bearer token guarding the MCP/CLI server. Generated on first enable.
 */
mcp_server_token?: string; submit_paste_method?: PasteMethod; submit_key?: AutoSubmitKey; submit_idle_behavior?: SubmitIdleBehavior; cancel_behavior?: CancelBehavior; submit_clipboard_handling?: ClipboardHandling; clipboard_restore_delay?: ClipboardRestoreDelay; submit_clipboard_restore_delay?: ClipboardRestoreDelay; jumper_submit_delay?: JumperSubmitDelay; jumper_paste_delay?: JumperPasteDelay; jumper_submit_delay_remote?: JumperSubmitDelay; jumper_paste_delay_remote?: JumperPasteDelay; jumper_remote_match_strings?: string[]; return_focus_output?: boolean; return_focus_submit?: boolean; anchor_return_focus?: boolean; anchor_action_output_idle?: AnchorAction; anchor_action_output_stop?: AnchorAction; anchor_action_submit_idle?: AnchorAction; anchor_action_submit_stop?: AnchorAction; anchor_action_output_idle_slot?: number; anchor_action_output_stop_slot?: number; anchor_action_submit_idle_slot?: number; anchor_action_submit_stop_slot?: number; jumper_track_enabled?: boolean; jumper_track_slot?: number; jumper_track_output?: boolean; jumper_track_submit?: boolean; jumper_track_output_enabled?: boolean; jumper_track_output_slot?: number; jumper_track_submit_enabled?: boolean; jumper_track_submit_slot?: number; jumper_save_cursor_slots?: boolean[]; jumper_cursor_mode_slots?: CursorMode[]; anchor_on_finish_require_same_flow?: boolean; jumper_cursor_mode?: CursorMode; jumper_v2_migrated?: boolean; jumper_v3_migrated?: boolean; jumper_v4_migrated?: boolean;translator_enabled?: boolean; translator_folders?: TranslatorFolder[]; translator_seeded?: boolean; translator_priority?: TranslatorPriority; translator_model?: string; translator_model_unload_timeout?: ModelUnloadTimeout; translator_model_unload_custom_seconds?: number; translator_poll_secs?: number; jumper_persist?: boolean; jumper_saved_slots?: (SavedJumpSlot | null)[] }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type SubmitIdleBehavior = "start_normal" | "do_nothing" | "start_and_submit"
/**
 * What the cancel affordances (Escape shortcut, tray "Cancel", the in-app
 * cancel command, `handy --cancel`) do to the take in progress.
 */
export type CancelBehavior = "discard_recording" | "finish_silently"
export type ClipboardRestoreDelay = "none" | "ms250" | "ms500" | "ms1000" | "ms2500" | "ms5000"
export type JumperSubmitDelay = "none" | "ms100" | "ms250" | "ms500" | "ms1000" | "ms2000"
export type JumperPasteDelay = "none" | "ms100" | "ms250" | "ms500" | "ms1000" | "ms2000"
export type RegistrationFailure = { id: string; binding: string; error: string }
export type AnchorStatus = { app: string; control_class: string; stale: boolean; remote: boolean }
export type SavedJumpSlot = { app: string; window_class: string; control_class: string; cursor?: SavedCursor | null }
export type CursorMode = "AppRelative" | "ScreenAbsolute"
export type SavedCursor = { abs_x: number; abs_y: number; norm_x: number | null; norm_y: number | null; mode: CursorMode }
export type AnchorAction = "none" | "jump" | "set" | "clear"
export type TranslatorPriority = "live_first" | "folder_first" | "fifo"
export type TranslatorFolder = { path: string; enabled: boolean }
export type TranslatorStatus = { enabled: boolean; queue: string[]; queue_len: number; current_file: string | null; current_segment: number; current_total_segments: number; paused_reason: string | null; done_count: number; failed_count: number }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
/**
 * One provider's result for a single prompt.
 */
export type ChatOutcome = { provider_id: string; provider_name: string; model: string; ok: boolean; content: string; error: string | null; input_tokens: number | null; output_tokens: number | null; 
/**
 * USD cost: the real charge for OpenRouter, otherwise computed from the
 * provider's per-million rates. `None` when usage is unknown.
 */
cost_usd: number | null; 
/**
 * True when `cost_usd` is the provider-reported real charge (OpenRouter),
 * false when it is estimated from the configured per-million rates.
 */
cost_is_real: boolean; elapsed_ms: number }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = "Whisper" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "FlmWhisper" | "ApiWhisper" | 
/**
 * OpenRouter transcription (JSON + base64 audio via the dedicated STT
 * endpoint or chat `input_audio`). Unlike ApiWhisper it participates in
 * the live/chunked per-segment pipeline.
 */
"OpenRouterWhisper"
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; 
/**
 * Real USD cost of this transcription (OpenRouter usage.cost); `None` for
 * local/free engines or when the provider didn't report a cost.
 */
cost_usd?: number | null; 
/**
 * Recording length in seconds.
 */
duration_seconds?: number | null; 
/**
 * Human label of the engine/model that produced this transcription.
 */
model_used?: string | null }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
/**
 * A registered LLM provider. This single registry powers token counting, LLM
 * post-processing, and the model-testing tool. Post-processing and the tester
 * reference a provider by its stable `id` (surfaced in the UI as "#1", "#2",
 * â€¦); editing a provider here updates everywhere that references it.
 * 
 * `kind` selects the API dialect and the token-counting strategy:
 * - `anthropic`          â€” Anthropic Messages API (+ dedicated count_tokens)
 * - `gemini`             â€” Google Gemini (+ dedicated countTokens)
 * - `openai_local`       â€” bundled tiktoken; token counting only (no chat)
 * - `openai_compatible`  â€” OpenAI `/chat/completions` (FLM, LM Studio, Ollamaâ€¦)
 * - `openrouter`         â€” OpenAI-compatible **with real per-request cost**
 * - `apple_intelligence` â€” on-device Apple model (macOS ARM only)
 */
export type LlmProvider = { 
/**
 * Stable unique id; never changes once assigned, even if `name` changes.
 */
id: string; kind: string; enabled?: boolean; 
/**
 * User-facing display label.
 */
name: string; base_url?: string; 
/**
 * Whether the UI lets the user edit `base_url` (false for `openai_local`).
 */
allow_base_url_edit?: boolean; api_key?: string; model: string; 
/**
 * Provider/model supports OpenAI-style JSON-schema structured output.
 */
supports_structured_output?: boolean; 
/**
 * Cost in USD per 1,000,000 input tokens. Ignored when `reports_cost()`
 * (OpenRouter returns the real charge) or for free/local providers.
 */
cost_input_per_million?: number; 
/**
 * Cost in USD per 1,000,000 output tokens.
 */
cost_output_per_million?: number; 
/**
 * Providers sharing a non-empty group run serially against each other when
 * `sequential` is set (e.g. all FLM services share one model loader).
 */
concurrency_group?: string; 
/**
 * When true, do not run concurrently with others in `concurrency_group`.
 */
sequential?: boolean; 
/**
 * When true, the user-entered cost is frozen: the automatic OpenRouter
 * price lookup on model change will not overwrite it.
 */
persist_price?: boolean }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Status of the localhost MCP/CLI server, for the settings UI.
 */
export type McpStatus = { enabled: boolean; running: boolean; port: number; 
/**
 * Bearer token for configuring an MCP client (localhost only).
 */
token: string; cli_installed: boolean; cli_path: string }
export type RestoreReport = { settings_restored: boolean; history_restored: boolean; recordings_restored: number; restart_required: boolean; errors: string[] }
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; is_custom: boolean }
/**
 * One Vulkan GPU adapter offered to the frontend's device-selection dropdown
 * (T-212). Trimmed down from `transcribe_rs::engines::whisper::GpuDeviceInfo`
 * — the UI only needs an id to persist and a label to show.
 */
export type GpuDeviceOption = { index: number; name: string; vram_total_mb: number }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * The model-testing prompt library: separately-saved model and judge prompts,
 * plus combined presets (a model prompt + judge prompt under one name).
 */
export type ModelTestLibrary = { model_prompts?: NamedText[]; judge_prompts?: NamedText[]; presets?: ModelTestPreset[] }
/**
 * A saved model-testing preset: a model prompt paired with a judge prompt.
 * Presets reference the saved prompts that make them up (so selecting a preset
 * also selects its parts in the prompt pickers); the raw-text fields are kept
 * as a fallback for pre-0.18 presets and when a referenced prompt is deleted.
 */
export type ModelTestPreset = { id: string; name: string; model_prompt_id?: string | null; judge_prompt_id?: string | null; model_prompt?: string; judge_prompt?: string }
export type ModelTestRun = { outcomes: ChatOutcome[]; 
/**
 * Wall-clock from dispatch until the last provider finished (ms).
 */
round_trip_ms: number }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "custom" | "sec_5"
/**
 * An image attached to a saved model prompt, persisted as a base64 data URL so
 * it survives restarts as part of the prompt library.
 */
export type NamedImage = { name: string; data_url: string }
/**
 * A named, reusable text entry â€” a saved model or judge prompt for the
 * model-testing tool.
 */
export type NamedText = { id: string; name: string; text: string; 
/**
 * Optional attached image (model prompts only; judge prompts leave this
 * `None`). Persisted so a saved prompt restores its picture.
 */
image?: NamedImage | null }
/**
 * One OpenRouter model's pass-through pricing, normalized to USD per 1M tokens.
 */
export type OpenRouterModelPrice = { id: string; canonical_slug: string; name: string; input_per_million: number; output_per_million: number }
/**
 * Which OpenRouter endpoint the OpenRouter transcription engine uses.
 */
export type OpenRouterTranscriptionRoute = 
/**
 * Dedicated `/audio/transcriptions` JSON endpoint (Whisper-style models).
 */
"stt" | 
/**
 * Chat `/chat/completions` with an `input_audio` part (audio-capable LLMs).
 */
"chat"
export type OverlayPosition = "none" | "top" | "bottom"
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type ProviderCountResult = { provider_id: string; provider_name: string; model: string; ok: boolean; tokens: number | null; error: string | null; elapsed_ms: number }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Audio container sent to remote (OpenRouter) transcription. Opus is ~10Ã—
 * smaller than WAV â€” light on bandwidth â€” but support varies by model.
 */
export type TranscriptionAudioFormat = "wav" | "opus"
export type TranscriptionMode = "live" | "post_recording"
export type Theme = "system" | "light" | "dark"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
